#!/usr/bin/env bash

# get scripts base regardless of execution location
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
scriptsBase="$(dirname "$SOURCE")/scripts"
. "$scriptsBase/init"

set -e
case "$1" in
"install")
  if [[ "$2" != "skip" ]]; then
    "$scriptsBase/build" "$2"
  fi
  mvn clean install
  ;;
"package")
  if [[ "$2" != "skip" ]]; then
    "$scriptsBase/build" "$2"
  fi
  mvn clean package
  ;;
"build")
  if [[ "$2" != "skip" ]]; then
    "$scriptsBase/build" "$2"
  fi
  mvn -N install
  (cd "${NAME}-API" && mvn clean install)
  (cd "${NAME}-Server" && mvn clean package)
  ;;
"apply" | "patch")
  "$scriptsBase/build" "$2"
  ;;
"rb")
  "$scriptsBase/rebuildpatches"
  ;;
"update")
  "$scriptsBase/update" "$2" "$3"
  ;;
*)
  echo "Wyvern is a project focusing on improving Minecraft software. We provide a variety of scripts to manage Wyvern's environment."
  echo "You can improve the scripts by creating a pull request, and we would be so grateful if you do so!"
  echo ""
  echo "List of commands:"
  ;;
esac
set +e
