#!/usr/bin/env bash

# get scripts base regardless of execution location
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
scriptsBase="$(dirname "$SOURCE")/scripts"
. "$scriptsBase/init"

set -e
case "$1" in
        "apply" | "patch")
        "$scriptsBase/build" "$2"
    ;;
        "rebuild" | "rb")
        "$scriptsBase/rebuildpatches"
    ;;
        "update" | "upgrade")
        "$scriptsBase/update" "$2" "$3" "$4"
    ;;
    *)
        echo "Wyvern is an active project focuses on improving vanilla Minecraft without sacrificing"
        echo "any expected behaviors or features. We provides several scripts for you to interact with"
        echo "this repository just as easy as a breeze"
        echo ""
        echo "  List of commands:"
        echo "    apply    │  decompile then apply patches on top of Minecraft"
        echo "    rebuild  │  rebuild the patches"
        echo "    update   │  update the decompiler or the remapper"
    ;;
esac
set +e
