#!/usr/bin/env bash

# get scripts Base regardless of execution location
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
scriptsBase="$(dirname "$SOURCE")"
. "$scriptsBase/init"

bin="$remapper/target"
jarDownload="https://piston-data.mojang.com/v1/objects/f69c284232d7c7580bd89a5a4931c3581eae1378/server.jar" # 1.19.2
mappingDownload="https://piston-data.mojang.com/v1/objects/ed5e6e8334ad67f5af0150beed0f3d156d74bd57/server.txt" # 1.19.2
jarPath="$remapper/META-INF/versions/${VERSION}/server-${VERSION}.jar"
jar="$fernflower/server-${VERSION}.jar"
mappingLocation="$remapper/server.txt"

(

    git submodule update --init --recursive
	mvn clean install
    cd "$remapper"
    curl "$jarDownload" > server-bundle.jar
    jar xf server-bundle.jar META-INF/versions/${VERSION}/server-${VERSION}.jar
    curl "$mappingDownload"	-O
    mvn clean install

    cd "$bin"
    delete "$fernflower" "mkdir"
    java -jar SpecialSource-1.11.0-shaded.jar -live -i "$jarPath" -o "$jar" -m "$mappingLocation"

) || exit 1