#!/usr/bin/env bash

# get scripts Base regardless of execution location
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
scriptsBase="$(dirname "$SOURCE")"
. "$scriptsBase/init"

bin="$remapper/target"
jarDownload="https://launcher.mojang.com/v1/objects/c8f83c5655308435b3dcf03c06d9fe8740a77469/server.jar" # 1.18.2
mappingDownload="https://launcher.mojang.com/v1/objects/e562f588fea155d96291267465dc3323bfe1551b/server.txt" # 1.18.2
jarPath="$remapper/META-INF/versions/${VERSION}/server-${VERSION}.jar"
jar="$fernflower/server-${VERSION}.jar"
ssJar="SpecialSource-1.11.4-SNAPSHOT-shaded.jar"
mappingLocation="$remapper/server.txt"

(

    git submodule update --init --recursive
	mvn clean install
    cd "$remapper"
    curl "$jarDownload" > server-bundle.jar
    jar xf server-bundle.jar META-INF/versions/${VERSION}/server-${VERSION}.jar
    curl "$mappingDownload"	-O
    mvn clean install

    cd "$bin"
    delete "$fernflower" "mkdir"
    java -jar "$ssJar" -live -i "$jarPath" -o "$jar" -m "$mappingLocation"

) || exit 1